@startuml
actor Cliente
skinparam Style strictuml
participant CatalogController
participant TaskCatalog
participant FactoryCatalog
participant CatalogItemController
participant "session : Session"
participant ProductController
box Server
    participant Server
    database Database
end box


Cliente -> CatalogController : showView()
CatalogController->TaskCatalog **
CatalogController->TaskCatalog : call()
activate TaskCatalog
TaskCatalog->Server : getAllProducts()
activate Server
Server->Database : getAll()
activate Database 
return ArrayList<Product>
return String
return List <Node>

opt Selezione sezione
Cliente -> CatalogController : Selezione sezione
end opt
opt Selezione ordinamento
Cliente -> CatalogController : Selezione ordinamento
end opt
activate CatalogController
CatalogController->CatalogController : refresh()
activate CatalogController
CatalogController->FactoryCatalog : getCatalogList(List<Node>)
activate FactoryCatalog
loop Numero di prodotti
FactoryCatalog -> CatalogItemController **: createCatalogItem()
activate CatalogItemController
return Node
end loop
return List<Node>
deactivate CatalogController

activate CatalogItemController

opt Aggiungi al carrello da catalogo
Cliente -> CatalogItemController : Selezione quantità
 
Cliente -> CatalogItemController : Click carrello

CatalogItemController -> CatalogItemController : handleAddToCartAction() 
activate CatalogItemController
CatalogItemController -> "session : Session" ** : getIstance()
CatalogItemController -> "session : Session" : addProduct()
deactivate CatalogItemController
end opt 

Cliente -> CatalogItemController : Click su immagine
CatalogItemController -> ProductController **: showView()
activate ProductController
opt Aggiungi al carrello da catalogo
Cliente -> ProductController : Selezione quantità
 
Cliente -> ProductController : Click carrello

ProductController -> ProductController : handleAddToCartAction() 
activate ProductController
ProductController -> "session : Session" ** : getIstance()
ProductController -> "session : Session" : addProduct()

@enduml